"""Renders one per-tag server module, composing its tools and resources."""

from typing import Any

from ..fastmcp_target import FastMCPTarget
from ..models import ModuleSpec
from ..utils import camel_to_snake
from .resources import generate_resource_for_endpoint, render_resource
from .tools import generate_tool_for_method


def generate_server_module(
    api_var_name: str,
    api_class: Any,
    resource_endpoints: list[dict[str, Any]] | None = None,
    validate_output: bool | None = None,
    exclude_methods: set[str] | None = None,
    body_schemas: dict[str, dict] | None = None,
    target: FastMCPTarget | None = None,
) -> ModuleSpec:
    """Generate a single server module for one API class.

    Args:
        api_var_name: API instance variable name (e.g., 'pet_api')
        api_class: API class from generated OpenAPI client
        resource_endpoints: Optional list of GET endpoints to generate as resources
        validate_output: validate_output flag (None = server default)
        exclude_methods: Method names already generated by earlier modules (first-tag-wins dedup).
            Any method in this set is skipped, and newly generated methods are added to it.
        body_schemas: Mapping of method_name → simplified body schema for form data coercion.
    """
    api_class_name = api_class.__name__
    module_name = api_var_name.replace("_api", "").title().replace("_", "")

    # Header
    code = f'''"""
{module_name} MCP Server Module.

Auto-generated from {api_class_name}.
DO NOT EDIT MANUALLY - regenerate using: python src/mcp_generator.py
"""

import asyncio
import logging
from pathlib import Path
from typing import Any
import sys

from fastmcp import FastMCP, Context

# Add the generated folder to the Python path so we can import openapi_client
generated_path = Path(__file__).parent.parent.parent / "generated_openapi"
if str(generated_path) not in sys.path:
    sys.path.insert(0, str(generated_path))

from openapi_py_fetch import ApiClient, ApiException
from openapi_client import {api_class_name}

logger = logging.getLogger(__name__)

# Create FastMCP server for this module
mcp = FastMCP("{module_name}")


def _format_api_error(e: ApiException) -> str:
    """Format API exception into user-friendly error message."""
    if e.status == 401:
        return "Authentication required. User token invalid or missing."
    elif e.status == 403:
        return "Permission denied. Your role does not allow this action."
    elif e.status == 404:
        return "Resource not found."
    elif e.status == 500:
        return "Backend server error."
    else:
        return f"API error (status {{e.status}}): {{e.reason}}"


def _get_api_instances(openapi_client: ApiClient) -> dict:
    """Create API instances with the given client."""
    return {{
        '{api_var_name}': {api_class_name}(openapi_client)
    }}


class _ParameterValidationError(Exception):
    """Raised when a tool parameter cannot be parsed from JSON."""
    pass

'''

    # Embed _coerce_form_data helper when any method in this module has a body schema
    # The helper reshapes flat form key-value pairs into the nested structure the API expects.
    _module_methods = {
        n for n in dir(api_class) if not n.startswith("_") and callable(getattr(api_class, n, None))
    }
    _has_coercible = body_schemas and any(m in body_schemas for m in _module_methods)
    if _has_coercible:
        code += '''
def _coerce_form_data(data: dict, schema: dict) -> dict:
    """Coerce flat form data into the nested structure the API expects.

    Form UIs send flat key-value string pairs, but REST APIs often require
    nested objects, typed arrays, integers, etc.  This function reshapes each
    field according to the body schema extracted from the OpenAPI spec at
    generation time.
    """
    import json as _json

    coerced: dict = {}
    for key, value in data.items():
        field_schema = schema.get(key)
        if field_schema is None:
            coerced[key] = value
            continue

        field_type = field_schema.get("type", "string")

        if field_type == "array":
            items_schema = field_schema.get("items", {})
            items_type = items_schema.get("type", "string")
            if isinstance(value, list):
                coerced[key] = value
            elif isinstance(value, str):
                try:
                    parsed = _json.loads(value)
                    coerced[key] = parsed if isinstance(parsed, list) else [parsed]
                except (ValueError, _json.JSONDecodeError):
                    parts = [v.strip() for v in value.split(",") if v.strip()]
                    if items_type == "object":
                        # Wrap each plain string into an object keyed by the first string property
                        item_props = items_schema.get("properties", {})
                        name_key = next(
                            (pk for pk, pv in item_props.items() if pv.get("type") == "string"),
                            "name",
                        )
                        coerced[key] = [{name_key: p} for p in parts]
                    else:
                        coerced[key] = parts
            else:
                coerced[key] = [value]

        elif field_type == "object":
            props = field_schema.get("properties", {})
            if isinstance(value, dict):
                coerced[key] = value
            elif isinstance(value, str):
                try:
                    parsed = _json.loads(value)
                    coerced[key] = parsed
                except (ValueError, _json.JSONDecodeError):
                    # Wrap plain string into an object using the first string property
                    name_key = next(
                        (pk for pk, pv in props.items() if pv.get("type") == "string"),
                        "name",
                    )
                    coerced[key] = {name_key: value}
            else:
                coerced[key] = value

        elif field_type == "integer":
            try:
                coerced[key] = int(value)
            except (ValueError, TypeError):
                coerced[key] = value

        elif field_type == "number":
            try:
                coerced[key] = float(value)
            except (ValueError, TypeError):
                coerced[key] = value

        elif field_type == "boolean":
            if isinstance(value, str):
                coerced[key] = value.lower() in ("true", "1", "yes")
            else:
                coerced[key] = bool(value)

        else:
            coerced[key] = value

    return coerced

'''

    code += """
# Generated tool functions
# ============================================================================

"""

    # Generate tools for this API
    # Derive tag name from api_var_name (e.g., 'pet_api' -> 'pet')
    tag_name = api_var_name.replace("_api", "")
    tool_count = 0
    for method_name in dir(api_class):
        if method_name.startswith("_"):
            continue

        method = getattr(api_class, method_name)
        if not callable(method):
            continue

        # First-tag-wins dedup: skip methods already generated by an earlier module
        if exclude_methods is not None and method_name in exclude_methods:
            continue

        tool_code = generate_tool_for_method(
            api_var_name,
            method_name,
            method,
            tag_name=tag_name,
            validate_output=validate_output,
            body_schemas=body_schemas,
            target=target,
        )
        if tool_code:
            code += tool_code
            tool_count += 1
            # Record this method so later modules skip it
            if exclude_methods is not None:
                exclude_methods.add(method_name)

    # Generate resource templates if requested
    resource_count = 0
    if resource_endpoints:
        code += """

# Generated resource templates
# ============================================================================

"""
        for endpoint in resource_endpoints:
            operation_id = endpoint["operation_id"]
            # Convert camelCase operation_id to snake_case method name
            # getPetById -> get_pet_by_id
            method_name = camel_to_snake(operation_id)

            if not hasattr(api_class, method_name):
                continue

            resource_spec = generate_resource_for_endpoint(api_var_name, endpoint, method_name)

            if resource_spec:
                resource_code = render_resource(resource_spec)
                code += resource_code
                resource_count += 1

    # Footer
    code += f"""

# Generated {tool_count} tools and {resource_count} resources for {api_class_name}
"""

    filename = f"{api_var_name.replace('_api', '')}_server.py"

    return ModuleSpec(
        filename=filename,
        api_var_name=api_var_name,
        api_class_name=api_class_name,
        module_name=module_name,
        tool_count=tool_count,
        code=code,
        resource_count=resource_count,
        tag_name=tag_name,
    )
