"""
Template generation for FastMCP 3.1 multi-auth validation tests.

Generates tests that verify MultiAuth, PropelAuth, and authentication
composition in the generated server.
"""

from ....models import ApiMetadata, ModuleSpec, SecurityConfig


def generate_multi_auth_tests(
    api_metadata: ApiMetadata,
    security_config: SecurityConfig,
    modules: dict[str, ModuleSpec],
) -> str:
    """Generate tests for FastMCP 3.1 multi-auth features.

    Args:
        api_metadata: API metadata
        security_config: Security configuration
        modules: Generated server modules

    Returns:
        str: Test file content for multi-auth validation
    """

    return f'''"""
Generated Multi-Auth Tests for {api_metadata.title}

Tests for FastMCP 3.1 authentication features:
- MultiAuth (composing multiple token verifiers)
- PropelAuth (enterprise authentication provider)
- JWT verifier fallback behavior

These tests verify that authentication providers are correctly
configured based on the fastmcp.json feature flags.

Generated by mcp_generator - DO NOT EDIT MANUALLY
"""

import json
import os
import sys
from pathlib import Path

import pytest
import httpx


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture
def fastmcp_config():
    """Load and return fastmcp.json configuration."""
    config_path = Path(__file__).parent.parent / "fastmcp.json"
    if not config_path.exists():
        config_path = Path(__file__).parent.parent.parent / "generated_mcp" / "fastmcp.json"
    if not config_path.exists():
        pytest.skip("fastmcp.json not found")
    with open(config_path, encoding="utf-8") as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# MultiAuth configuration
# ---------------------------------------------------------------------------


class TestMultiAuthConfig:
    \"\"\"Tests for MultiAuth feature configuration.\"\"\"

    def test_multi_auth_config_present(self, fastmcp_config):
        \"\"\"fastmcp.json should contain multi_auth feature config.\"\"\"
        features = fastmcp_config.get("features", {{}})
        assert "multi_auth" in features

    def test_multi_auth_disabled_by_default(self, fastmcp_config):
        \"\"\"MultiAuth should be disabled by default.\"\"\"
        ma = fastmcp_config["features"]["multi_auth"]
        assert ma.get("enabled") is False

    def test_multi_auth_has_providers_list(self, fastmcp_config):
        \"\"\"MultiAuth should have a providers list.\"\"\"
        ma = fastmcp_config["features"]["multi_auth"]
        assert "providers" in ma
        assert isinstance(ma["providers"], list)


# ---------------------------------------------------------------------------
# PropelAuth configuration
# ---------------------------------------------------------------------------


class TestPropelAuthConfig:
    \"\"\"Tests for PropelAuth feature configuration.\"\"\"

    def test_propelauth_config_present(self, fastmcp_config):
        \"\"\"fastmcp.json should contain propelauth feature config.\"\"\"
        features = fastmcp_config.get("features", {{}})
        assert "propelauth" in features

    def test_propelauth_disabled_by_default(self, fastmcp_config):
        \"\"\"PropelAuth should be disabled by default.\"\"\"
        pa = fastmcp_config["features"]["propelauth"]
        assert pa.get("enabled") is False

    def test_propelauth_has_required_fields(self, fastmcp_config):
        \"\"\"PropelAuth config should have auth_url, client_id, and client_secret fields.\"\"\"
        pa = fastmcp_config["features"]["propelauth"]
        assert "auth_url" in pa
        assert "introspection_client_id" in pa
        assert "introspection_client_secret" in pa

    def test_propelauth_has_optional_fields(self, fastmcp_config):
        \"\"\"PropelAuth config should have base_url and required_scopes fields.\"\"\"
        pa = fastmcp_config["features"]["propelauth"]
        assert "base_url" in pa
        assert "required_scopes" in pa


# ---------------------------------------------------------------------------
# Auth middleware wiring
# ---------------------------------------------------------------------------


class TestAuthMiddlewareWiring:
    \"\"\"Tests for authentication middleware in the generated server.\"\"\"

    def test_middleware_dir_exists(self):
        \"\"\"middleware/ directory should exist in the generated server.\"\"\"
        middleware_path = Path(__file__).parent.parent / "middleware"
        if not middleware_path.exists():
            middleware_path = Path(__file__).parent.parent.parent / "generated_mcp" / "middleware"
        assert middleware_path.exists(), "middleware/ directory not found"

    def test_oauth_provider_module_exists(self):
        \"\"\"middleware/oauth_provider.py should exist.\"\"\"
        for base in [
            Path(__file__).parent.parent,
            Path(__file__).parent.parent.parent / "generated_mcp",
        ]:
            oauth_path = base / "middleware" / "oauth_provider.py"
            if oauth_path.exists():
                return
        pytest.fail("oauth_provider.py not found in middleware/")

    def test_oauth_provider_has_multi_auth(self):
        \"\"\"oauth_provider.py should contain create_multi_auth_verifier.\"\"\"
        for base in [
            Path(__file__).parent.parent,
            Path(__file__).parent.parent.parent / "generated_mcp",
        ]:
            oauth_path = base / "middleware" / "oauth_provider.py"
            if oauth_path.exists():
                content = oauth_path.read_text(encoding="utf-8")
                assert "def create_multi_auth_verifier" in content
                return
        pytest.skip("oauth_provider.py not found")

    def test_oauth_provider_has_propelauth(self):
        \"\"\"oauth_provider.py should contain create_propelauth_provider.\"\"\"
        for base in [
            Path(__file__).parent.parent,
            Path(__file__).parent.parent.parent / "generated_mcp",
        ]:
            oauth_path = base / "middleware" / "oauth_provider.py"
            if oauth_path.exists():
                content = oauth_path.read_text(encoding="utf-8")
                assert "def create_propelauth_provider" in content
                return
        pytest.skip("oauth_provider.py not found")

    @pytest.mark.asyncio
    async def test_unauthenticated_request_rejected_when_validate_tokens(
        self, mcp_server_url, fastmcp_config
    ):
        \"\"\"When validate_tokens is true, unauthenticated requests should be rejected.\"\"\"
        validate = (
            fastmcp_config.get("middleware", {{}})
            .get("config", {{}})
            .get("authentication", {{}})
            .get("validate_tokens", False)
        )
        if not validate:
            pytest.skip("validate_tokens not enabled in fastmcp.json")

        try:
            async with httpx.AsyncClient(timeout=5.0) as client:
                response = await client.post(
                    mcp_server_url,
                    json={{
                        "jsonrpc": "2.0",
                        "id": "unauth",
                        "method": "initialize",
                        "params": {{
                            "protocolVersion": "2025-03-26",
                            "capabilities": {{}},
                            "clientInfo": {{"name": "test", "version": "1.0"}}
                        }}
                    }},
                    headers={{"Content-Type": "application/json"}},
                )
                # Should be 401 or 403 when no token is provided
                assert response.status_code in (401, 403), (
                    f"Expected 401/403 without auth, got {{response.status_code}}"
                )
        except (httpx.ConnectError, httpx.TimeoutException):
            pytest.skip("MCP server not available")
'''
