"""
Template generation for the generated test suite's conftest.

Fixtures every generated test module shares live here. pytest discovers a
conftest automatically, so hoisting a fixture into it removes the duplicate
without adding an import to any test file.
"""

from ...config import DEFAULT_GENERATED_MCP_URL
from ...models import ApiMetadata


def generate_test_conftest(api_metadata: ApiMetadata) -> str:
    """Generate conftest.py with the fixtures shared across generated tests."""
    return f'''"""
Shared fixtures for generated {api_metadata.title} tests.

Generated by mcp_generator - DO NOT EDIT MANUALLY
"""

import os

import pytest

# Override with the MCP_SERVER_URL environment variable.
DEFAULT_MCP_SERVER_URL = "{DEFAULT_GENERATED_MCP_URL}"


def mcp_url() -> str:
    """The MCP endpoint under test."""
    return os.getenv("MCP_SERVER_URL", DEFAULT_MCP_SERVER_URL)


@pytest.fixture
def mcp_server_url() -> str:
    """MCP Server URL."""
    return mcp_url()


@pytest.fixture
def mcp_server_base() -> str:
    """MCP Server base URL (without the /mcp path)."""
    return mcp_url().replace("/mcp", "")
'''
